import { useState, useEffect } from "react";
import axios from "axios";
import { FaExclamationTriangle, FaChartLine } from "react-icons/fa";

function SystemPredictionCard() {
  const [prediction, setPrediction] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const axiosInstance = axios.create({
    baseURL: "http://localhost:8080",
    withCredentials: true,
  });

  useEffect(() => {
    const fetchPrediction = async () => {
      try {
        setLoading(true);
        const response = await axiosInstance.get(
          "/api/public/prediction/system"
        );
        setPrediction(response.data.predicted_cases);
        setError(null);
      } catch (err) {
        if (err.response?.status === 401) {
          setError(
            "System prediction service unavailable. Please try again later."
          );
        } else if (err.response?.status === 500) {
          setError("Server error occurred while fetching prediction.");
        } else {
          setError(
            "Oops! Unable to connect to the prediction service. Weekly data not added—please try again soon!"
          );
        }
      } finally {
        setLoading(false);
      }
    };

    fetchPrediction();
  }, []);

  return (
    <div className="p-6 bg-gray-100 rounded-lg shadow-md">
      <h4 className="text-lg font-semibold text-black mb-4 border-l-4 border-red-500 pl-3 flex items-center gap-2">
        <FaChartLine /> System Dengue Case Prediction (This Week)
      </h4>

      {loading ? (
        <div className="text-center py-4">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
          <p className="mt-2 text-gray-600">Loading prediction...</p>
        </div>
      ) : error ? (
        <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded">
          <div className="flex items-center gap-2">
            <FaExclamationTriangle />
            <strong>Error:</strong> {error}
          </div>
        </div>
      ) : (
        <div className="text-center">
          <div className="text-5xl font-bold text-red-600 my-4">
            {Math.round(prediction)}
          </div>
          <p className="text-gray-600">
            Predicted dengue cases for your area this week
          </p>
          <div className="mt-4 p-3 bg-white rounded-lg shadow-inner">
            <p className="text-sm text-gray-700">
              <span className="font-semibold">Note:</span> This prediction is
              generated by our AI system based on current trends and historical
              data.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

export default SystemPredictionCard;
